#!/bin/sh
$(date --date="today" +%T >> first.snap)
$(echo "===================================================" >> first.snap)
$(who | grep "$($whoami)" | grep -o "tty[0-9]\s" >> first.snap)
$(echo "===================================================" >> first.snap)
$(pwd >> first.snap)
$(echo "===================================================" >> first.snap)
$(echo $HOME >>first.snap)
$(echo "===================================================" >> first.snap)
$(who -H >> first.snap)
$(echo "===================================================" >> first.snap)
$(ps >> first.snap)
$(echo "===================================================" >> first.snap)
$(stty >> first.snap)
$(echo "===================================================" >> first.snap)
